{% set name = "pisces" %}
{% set version = "0.4.4" %}


package:
  name: {{ name|lower }}-db
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pisces-{{ version }}.tar.gz
  sha256: 1f6d174bd0087a5e39ad4dcf60a25d32d5a65ce9b802b2ce1c5f6180a3bae29b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pisces = pisces.commands.main:cli

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click
    - numpy
    - obspy >=1.4.1
    - python >={{ python_min }}
    - sqlalchemy >=1.4

test:
  imports:
    - pisces
    - pisces.commands
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/LANL-Seismoacoustics/pisces
  summary: A Practical Seismological Database Library in Python.
  license: MIT
  license_file: LICENSE.txt
  description: |
    Pisces is a Python library that connects your geophysical analysis
    environment to a SQL database that uses the Center for Seismic 
    Studies (CSS) 3.0 or NNSA KB Core table schema.
  doc_url: https://lanl-seismoacoustics.github.io/pisces/
  dev_url: https://github.com/lanl-seismoacoustics/pisces/

extra:
  recipe-maintainers:
    - samuelchodur
