{% set name = "pisces" %}
{% set version = "0.4.2" %}


package:
  name: {{ name|lower }}-db
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pisces-{{ version }}.tar.gz
  sha256: b8f67ca813664e316403a5682081c5c0cc76a6bbbbb061cacd950fa164158ee1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pisces = pisces.commands.main:cli

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click
    - numpy
    - obspy >=1.0
    - python >=3.7
    - sqlalchemy >=1.4

test:
  imports:
    - pisces
    - pisces.commands
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LANL-Seismoacoustics/pisces
  summary: A Practical Seismological Database Library in Python.
  license: MIT
  license_file: LICENSE.txt
  description: |
    Pisces is a Python library that connects your geophysical analysis
    environment to a SQL database that uses the Center for Seismic 
    Studies (CSS) 3.0 or NNSA KB Core table schema.
  doc_url: https://lanl-seismoacoustics.github.io/pisces/
  dev_url: https://github.com/lanl-seismoacoustics/pisces/

extra:
  recipe-maintainers:
    - samuelchodur
